version: '3'

services:
    wmiadventure-backend:

        image: wmiadventure.azurecr.io/wmiadventure:v1
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000

        ports:
            - 8000:8000
    
    wmiadventure-frontend:
    
        image: wmiadventure.azurecr.io/frontend:v1
        build: ./frontend
        command: npm run start PORT=80

        ports:
            - 80:80
